name: turi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  get:
  dio:
  flutter_easyloading:
  flutter_screenutil:
  google_fonts:
  logger:
  connectivity_plus: ^4.0.2
  url_launcher:
  shared_value:
  intl:
  any_image_view:
  easy_debounce:
  font_awesome_flutter:
  flutter_spinkit:
  skeletonizer: ^2.0.1
  dropdown_search:
  carousel_slider:
  carousel_indicator:
  flutter_staggered_animations:
  dynamic_height_grid_view:
  persistent_bottom_nav_bar:
  flutter_gallery_3d:
  badges:
  flutter_rating_bar:
  animations:
  pinput:
  timeline_tile:
  flutter_dotenv:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - .env

